In [1]:
import pandas as pd
import time
import requests
import pprint
import json
import numpy as np

In [32]:
data_2019 = pd.read_csv('2019_reddit_scraped.csv', index_col = 2)
# data.rename({'transformed date':'date'})
# data = data.set_index('date')
data_2019 = data_2019.drop('Unnamed: 0', axis = 1)
data_2019.index = pd.to_datetime(data_2019.index, unit='s')

In [33]:
data_2019.resample('M').sum()

              score  num comments
utc date
2019-01-31    13308        211545
2019-02-28   306735        161595
2019-03-31   735565        176153
2019-04-30   542832        121702
2019-05-31   957964        245454
2019-06-30   880865        209546
2019-07-31  1055445        222132
2019-08-31  2017727        448237
2019-09-30  1083021        209654
2019-10-31   793705        160061
2019-11-30   164354        187336
2019-12-31    11140        171683
2020-01-31      111          1844

In [34]:
data_2018 = pd.read_csv('2018_reddit_scraped.csv', index_col = 1)
# data.rename({'transformed date':'date'})
# data = data.set_index('date')
# data = data.drop('Unnamed: 0', axis = 1)
data_2018.index = pd.to_datetime(data_2018.index, unit='s')

In [35]:
data_2018.resample('M').sum()

              score  num comments
utc date
2018-01-31   787617        257003
2018-02-28   736921        242075
2018-03-31  1001330        280302
2018-04-30   906155        267995
2018-05-31  1233364        317234
2018-06-30  1133516        338133
2018-07-31   851574        235109
2018-08-31  1397746        451371
2018-09-30   843534        222839
2018-10-31    11661        182009
2018-11-30    17740        280324
2018-12-31    13072        203094
2019-01-31      427          6891

In [36]:
data_2017 = pd.read_csv('2017_reddit_scraped.csv', index_col = 1)
# data.rename({'transformed date':'date'})
# data = data.set_index('date')
# data = data.drop('Unnamed: 0', axis = 1)
data_2017.index = pd.to_datetime(data_2017.index, unit='s')

In [42]:
data_2017.resample('M').sum()

              score  num comments
utc date
2017-01-31   852871        277721
2017-02-28   665286        207339
2017-03-31   793611        252409
2017-04-30   859251        285348
2017-05-31  1168329        330772
2017-06-30   923993        286810
2017-07-31   975742        275747
2017-08-31  1611741        479146
2017-09-30   847022        239036
2017-10-31   987347        271155
2017-11-30  1157795        292998
2017-12-31   763335        215946
2018-01-31    11319          2780

In [41]:
!pip install afinn

Collecting afinn
  Downloading https://files.pythonhosted.org/packages/86/e5/ffbb7ee3cca21ac6d310ac01944fb163c20030b45bda25421d725d8a859a/afinn-0.1.tar.gz (52kB)
Building wheels for collected packages: afinn
  Building wheel for afinn (setup.py): started
  Building wheel for afinn (setup.py): finished with status 'done'
  Created wheel for afinn: filename=afinn-0.1-cp36-none-any.whl size=53456 sha256=83f562e9411447af4e64e0b21be1a2c3b154769686e0fae6eec558b6ff4250d8
  Stored in directory: C:\Users\luico\AppData\Local\pip\Cache\wheels\b5\1c\de\428301f3333ca509dcf20ff358690eb23a1388fbcbbde008b2
Successfully built afinn
Installing collected packages: afinn
Successfully installed afinn-0.1

In [43]:
from afinn import Afinn

df = data_2017.copy()

In [45]:
df.replace('', np.nan)

,submission id,score,num comments,title,text,tranformed date
utc date,,,,,,
2017-01-01 00:00:06,5lcgjv,43,7,Super Creep Joe Episode 3 - The Exiled Mega Creep,NaN,2017-01-01 00:00:06
2017-01-01 00:00:23,5lcgln,0,1,Ded gaem,It's 2017 and there's no update wtf vovlo,2017-01-01 00:00:23
2017-01-01 00:03:03,5lch0t,1,1,7.00 VOICE BUG,[removed],2017-01-01 00:03:03
2017-01-01 00:03:40,5lch4g,30,20,Would Drige be too strong if he was affected b...,Deathlust seems like a strong passive that wou...,2017-01-01 00:03:40
2017-01-01 00:09:42,5lci3z,38,6,I finally got my Aegis replica. What a way to ...,NaN,2017-01-01 00:09:42
...,...,...,...,...,...,...
2018-01-01 15:11:33,7nfju3,1,0,SG e-Sports has decided to withdraw from the s...,[deleted],2018-01-01 15:11:33
2018-01-01 15:12:14,7nfjyf,4,4,121/5000 SG e-Sports has decided to withdraw f...,NaN,2018-01-01 15:12:14
2018-01-01 15:13:24,7nfk6a,24,32,solo queue isnt fun anymore,"every single game theres someone crying, ragin...",2018-01-01 15:13:24
2018-01-01 15:15:35,7nfkjo,4,1,Sg esport &amp; paiN gaming will not play at S...,NaN,2018-01-01 15:15:35
2018-01-01 15:16:13,7nfkoo,1,3,Well that's a good way to start a new year,NaN,2018-01-01 15:16:13

In [48]:
df.isnull().any()
df.shape

(226800, 6)

In [50]:
df = df.dropna()
df.shape

(155696, 6)

In [52]:
afinn = Afinn()
afinn_title = []
for x in df['title']:
    afinn_title.append(afinn.score(x))
    
df['afinn_score_title'] = afinn_title 
df

C:\Users\luico\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,submission id,score,num comments,title,text,tranformed date,afinn_score_title
utc date,,,,,,,
2017-01-01 00:00:23,5lcgln,0,1,Ded gaem,It's 2017 and there's no update wtf vovlo,2017-01-01 00:00:23,0.0
2017-01-01 00:03:03,5lch0t,1,1,7.00 VOICE BUG,[removed],2017-01-01 00:03:03,0.0
2017-01-01 00:03:40,5lch4g,30,20,Would Drige be too strong if he was affected b...,Deathlust seems like a strong passive that wou...,2017-01-01 00:03:40,0.0
2017-01-01 00:11:47,5lcihe,6,6,"New on Visage, need tips for key binding","So, according to dotabuff, the only hero I hav...",2017-01-01 00:11:47,0.0
2017-01-01 00:13:19,5lcit0,5,1,7.00 Voice Bug.,In game party voice-chat is muted if you open ...,2017-01-01 00:13:19,0.0
...,...,...,...,...,...,...,...
2018-01-01 14:58:44,7nfhk7,0,6,Make Wind Ranger's Focus Fire cancellable,[deleted],2018-01-01 14:58:44,-2.0
2018-01-01 15:01:40,7nfi1v,0,0,100% win rate in 2018,[deleted],2018-01-01 15:01:40,4.0
2018-01-01 15:11:10,7nfjrb,0,7,Hello this is a vent thread to complain about ...,Nevermind that both heroes are massively commo...,2018-01-01 15:11:10,-2.0
2018-01-01 15:11:33,7nfju3,1,0,SG e-Sports has decided to withdraw from the s...,[deleted],2018-01-01 15:11:33,0.0
2018-01-01 15:13:24,7nfk6a,24,32,solo queue isnt fun anymore,"every single game theres someone crying, ragin...",2018-01-01 15:13:24,4.0

In [ ]:
afinn_text = []
for x in df['text']:
    afinn_text.append(afinn.score(x))
    
df['afinn_score_title'] = afinn_text 
df